### ISSUE TITLE
Put all knowledge onto Wallet Page.

### ISSUE THREAD

**Issue by rejon** [proofofhardware/proofofhardware.com#1]
https://github.com/proofofhardware/website/blob/master/survey/wallets.md

**Comment by rejon** [comment]
Yes, also good to ask for review in chat once you got all your knowledge down.

**Comment by qinfengling** [comment]
Update the survey 
https://github.com/proofofhardware/proofofhardware.com/commit/33e0b264abbdcd72fc2ff463046cff5f6d5487fc
