### ISSUE TITLE
Put all knowledge onto Bitcoin Fullnode Page

### ISSUE THREAD

**Issue by rejon** [proofofhardware/proofofhardware.com#3]
https://github.com/proofofhardware/website/blob/master/howto/make-bitcoin-fullnode.md

**Comment by rejon** [comment]
Yes, also good to ask for review in chat once you got all your knowledge down.

**Comment by qinfengling** [comment]
All knowledge down for bitcoin. 

diff: https://github.com/proofofhardware/proofofhardware.com/compare/master...bitcoin
