### ISSUE TITLE
Put all knowledge onto Ethereum Mining Page

### ISSUE THREAD

**Issue by rejon** [proofofhardware/proofofhardware.com#4]
https://github.com/proofofhardware/website/blob/master/howto/make-ethereum-miner.md

**Comment by rejon** [comment]
Yes, also good to ask for review in chat once you got all your knowledge down.

**Comment by qinfengling** [comment]
Add 2 way for Ethereum mining

diff: https://github.com/proofofhardware/proofofhardware.com/compare/master...eth-mining
