### ISSUE TITLE
Announce project with a tweet :)

### ISSUE THREAD

**Issue by rejon** [proofofhardware/proofofhardware.com#5]

**Comment by rejon** [comment]
Myself @clemsos @christopheradams and I can help here in announcing this :) Think good for you to lead on, can review it and the TWEET with me, then announce.

**Comment by rejon** [comment]
And what should the tweet look like?

**Comment by qinfengling** [comment]
@rejon Should we use the following as the manifesto of proofofhardware ?


Did you get lost in cryptocurrency maze? 
Do you want to setup your own fullnode or miner?
Or want to own the swiss army knife of cryptocurrency,
we are only focus in the effective way in Blockchain.
Find them in http://proofofhardware.com,
Follow us in https://twitter.com/proofofhardware, 
Everything is Open Source,  feel free to contribute https://github.com/proofofhardware/proofofhardware.com

**Comment by rejon** [comment]
Great :)

Yes, its the place people can start, rather than get lost in the past.

**Comment by rejon** [comment]
I like it.

**Comment by clemsos** [comment]
Yes! We can pin it in the twitter account after

Le lun. 25 juin 2018 à 17:34, Jon Phillips <notifications@github.com> a
écrit :

**Comment by qinfengling** [comment]
Twitter: 
https://twitter.com/qinfengling/status/1012563069174595584

Done
